"""empty message

Revision ID: 4f080fa9ebcc
Revises: e62ed14924b1
Create Date: 2022-01-12 15:39:50.558215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f080fa9ebcc'
down_revision = 'e62ed14924b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_main_name'), 'main', ['name'], unique=False)
    op.create_index(op.f('ix_main_slot'), 'main', ['slot'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_main_slot'), table_name='main')
    op.drop_index(op.f('ix_main_name'), table_name='main')
    # ### end Alembic commands ###
