"""empty message

Revision ID: 7c8c79169b93
Revises: 4f080fa9ebcc
Create Date: 2022-01-12 15:46:15.628235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8c79169b93'
down_revision = '4f080fa9ebcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_entry_uc', 'main', ['date', 'name', 'slot'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_entry_uc', 'main', type_='unique')
    # ### end Alembic commands ###
