"""empty message

Revision ID: 89da9a8d734a
Revises: 7c8c79169b93
Create Date: 2022-01-12 20:58:16.270932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89da9a8d734a'
down_revision = '7c8c79169b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.alter_column('main', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('main', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('main', 'id')
    # ### end Alembic commands ###
