"""empty message

Revision ID: e62ed14924b1
Revises: c29ce7b2915f
Create Date: 2022-01-12 15:28:12.517751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62ed14924b1'
down_revision = 'c29ce7b2915f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_column('main', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('main', 'date')
    # ### end Alembic commands ###
